name: 'Write for you by RaPa Learning'
description: 'Markdown and style linter'
inputs:
  markdown-options:
    description: 'Options to use while linting markdown'
    required: false
    default: '--ignore vale'
  vale-options:
    description: 'Options for style-linting with vale'
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        echo "mdlint options ${{ inputs.markdown-options }}"
        echo "vale-options ${{ inputs.vale-options }}"
      shell: bash
    - run: bash setup-styles.sh
      shell: bash
